  @@ -0,0 +1,19 @@
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: my-image-deployment
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: my-image
    template:
      metadata:
        labels:
          app: my-image
      spec:
        containers:
          - name: my-image
            image: nessrinepoly/my-image:latest
            ports:
              - containerPort: 8080